spring.application.name=pdfConverter
server.port=${PORT:8080}

# Individual file limit (Increase to 50MB)
spring.servlet.multipart.max-file-size=50MB

# Total request limit (Increase to 100MB for multiple photos)
spring.servlet.multipart.max-request-size=100MB

# Forces Spring to use disk for large files, saving Render's limited RAM
spring.servlet.multipart.file-size-threshold=2MB
